# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 23:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 7, 3, 23, 25, 24, 275847, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 7, 3, 23, 25, 32, 555377, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
